version: '3'

services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:14.0'
    container_name: my_custom_postgres
    ports:
      - "54320:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vueapi
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
        # Colima
    user: ${CURRENT_UID}

  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: my_custom_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
